# Generated by Django 4.2 on 2026-05-04 07:31

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('MASYARAKAT', 'Masyarakat'), ('PETUGAS', 'Petugas'), ('ADMIN', 'Admin')], default='MASYARAKAT', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='profil/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('kategori', models.CharField(choices=[('KEAMANAN', 'Keamanan'), ('KETERTIBAN', 'Ketertiban'), ('KEBERSIHAN', 'Kebersihan'), ('INFRASTRUKTUR', 'Infrastruktur'), ('LAINNYA', 'Lainnya')], default='LAINNYA', max_length=30)),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('DIVERIFIKASI', 'Diverifikasi'), ('DITUGASKAN', 'Ditugaskan'), ('MENUJU_LOKASI', 'Menuju Lokasi'), ('DIPROSES', 'Diproses'), ('SELESAI', 'Selesai'), ('DITOLAK', 'Ditolak'), ('KADALUARSA', 'Kadaluarsa')], default='MENUNGGU', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('alamat_kejadian', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='laporan/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kadaluarsa_at', models.DateTimeField(blank=True, null=True)),
                ('pelapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'laporan',
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('DIVERIFIKASI', 'Diverifikasi'), ('DITUGASKAN', 'Ditugaskan'), ('MENUJU_LOKASI', 'Menuju Lokasi'), ('DIPROSES', 'Diproses'), ('SELESAI', 'Selesai'), ('DITOLAK', 'Ditolak'), ('KADALUARSA', 'Kadaluarsa')], max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='app.laporan')),
            ],
            options={
                'db_table': 'status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('komentar', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laporan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app.laporan')),
            ],
            options={
                'db_table': 'rating_feedback',
            },
        ),
        migrations.CreateModel(
            name='Penanganan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penanganan', to='app.laporan')),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penanganan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'penanganan',
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('pesan', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifikasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_aktivitas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DokumentasiPenanganan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='dokumentasi/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('penanganan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumentasi', to='app.penanganan')),
            ],
            options={
                'db_table': 'dokumentasi_penanganan',
            },
        ),
    ]
