# Generated by Django 4.2 on 2026-05-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='kategori',
            field=models.CharField(choices=[('KEAMANAN', 'Gangguan Keamanan'), ('KETERTIBAN', 'Gangguan Ketertiban Umum'), ('PENYAKIT_MSY', 'Miras, prostitusi, Narkoba & Judi'), ('BENCANA', 'Bencana / Kejadian Khusus'), ('PENEGAKAN_PERDA', 'Pelanggaran Perda'), ('LAINNYA', 'Lainnya')], default='LAINNYA', max_length=30),
        ),
    ]
