# Generated by Django 4.2 on 2026-06-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_laporan_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jabatan',
            field=models.CharField(blank=True, choices=[('LURAH', 'Lurah'), ('KEPLING', 'Kepala Lingkungan'), ('KASI_TRANTIB', 'Kasi Trantibum'), ('STAFF_TRANTIB', 'staff Trantibum'), ('LAINNYA', 'Lainnya')], max_length=30, null=True),
        ),
    ]
