# Generated by Django 4.2 on 2026-06-06 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_jabatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penanganan',
            name='petugas',
        ),
        migrations.AddField(
            model_name='penanganan',
            name='petugas',
            field=models.ManyToManyField(related_name='penanganan', to=settings.AUTH_USER_MODEL),
        ),
    ]
