# Generated by Django 4.2 on 2026-06-24 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_penanganan_petugas_penanganan_petugas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentasipenanganan',
            name='foto',
            field=models.ImageField(upload_to='dokumentasi/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'avi', 'mov', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='laporan/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'avi', 'mov', 'webm'])]),
        ),
    ]
