# Generated by Django 4.2 on 2026-06-30 10:54

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_dokumentasipenanganan_foto_alter_laporan_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentasipenanganan',
            name='foto',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='dokumentasi/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'avi', 'mov', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='foto',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='laporan/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'avi', 'mov', 'webm'])]),
        ),
    ]
